spring.application.name=agencia-viagens-api
server.port=${SERVER_PORT:8080}

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:agencia_viagens}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.default-property-inclusion=non_null
spring.jackson.time-zone=America/Sao_Paulo

app.seed.enabled=${SEED_ENABLED:true}
app.seed.admin-username=${SEED_ADMIN_USER:admin}
app.seed.admin-password=${SEED_ADMIN_PASSWORD:admin123}
app.seed.user-username=${SEED_USER_USER:maria}
app.seed.user-password=${SEED_USER_PASSWORD:user123}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

logging.level.org.springframework.security=INFO
